### ISSUE TITLE
Additional key-value pairs for the latestcomment object

### ISSUE THREAD

**Issue by pimisi** [yookore/activity_engine#1]
For the author, hope it would not return localhost when it is completed? It should rather return a relative URI.
It also appears from the object that we would have to do a secondary call to get the comment author’s name and profile picture. It would be best if these can be included in the object to eliminate the need for a secondary api request call

**Comment by yookore** [comment]
This has been included in the payload now. However there are no updated profile links to fully test this out. Making a todo for this.
